/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE `prog_program` (
  `kod_prog` varchar(10) NOT NULL,
  `kod_pp` varchar(10) DEFAULT NULL COMMENT 'pusat pengajian',
  `namaprog_MY` varchar(100) NOT NULL,
  `namaprog_EN` varchar(100) DEFAULT NULL,
  `tempoh_prog` int(11) DEFAULT NULL,
  `kod_mqa` varchar(60) DEFAULT NULL,
  `kod_tahap` int(11) DEFAULT NULL,
  `prog_on` tinyint(1) DEFAULT 1,
  `user_add` varchar(50) DEFAULT NULL,
  `dt_add` datetime DEFAULT NULL,
  `user_edit` varchar(50) DEFAULT NULL,
  `dt_edit` datetime DEFAULT NULL,
  PRIMARY KEY (`kod_prog`) USING BTREE,
  UNIQUE KEY `IDX1` (`kod_prog`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci ROW_FORMAT=DYNAMIC;



/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;